name: 🔢 Hash Error
description: Open an issue about a package's hash is incorrect.
labels: ["bug"]
body:
- type: checkboxes
  attributes:
    label: Prerequisites
    options:
    - label: I have used the predefined issue title. (e.g. "xxx@xxx&#58; hash check failed")
      required: true
    - label: I have verified that I am using the latest version of Scoop and corresponding bucket.
      required: true
- type: input
  attributes:
    label: Package Name and Version
    description: Name and version of package (install name) which has incorrect hash.
    placeholder: e.g. 7zip@21.00 (not '7-Zip')
  validations:
    required: true
