name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: windows-latest
    strategy:
      matrix:
        shell: [powershell, pwsh]
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Need at least 2 commits to properly gather changed files for linting
          fetch-depth: 2
          path: 'my_bucket'
      - name: Checkout Scoop
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ScoopInstaller/Scoop
          path: 'scoop_core'
      - name: Install and cache test dependencies
        uses: potatoqualitee/psmodulecache@9e4b63833c22c1768d648e115a9c849afdda22a5 # v6.3
        with:
          modules-to-cache: BuildHelpers, Pester
          shell: ${{ matrix.shell }}
      - name: Run tests
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\my_bucket\bin\test.ps1
