name: Commented Pull Request

on:
  issue_comment:
    types: [ created ]

permissions:
  contents: read
  pull-requests: write

jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: PullRequestHandler
      uses: ScoopInstaller/GithubActions@main
      if: startsWith(github.event.comment.body, '/verify')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCOOP_BRANCH: develop
