name: Issues

on:
  issues:
    types: [opened, labeled]

permissions:
  # Auto hash fixing commits
  contents: write
  issues: write

jobs:
  issueHandler:
    name: Issue Handler
    if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run Issue Handler
        uses: ScoopInstaller/GithubActions@5bceeda181721d9d10a18fdcc3ddca6f33467ae6 # v3.0.0
