name: Lint Pull Request

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: read

jobs:
  pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: ScoopInstaller/GithubActions/lint-pr-title@5bceeda181721d9d10a18fdcc3ddca6f33467ae6 # v3.0.0
